version: '3.8'

services:
    frontend:
        image: segma-vue-components:1.0.3
        container_name: segma-vue-components
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:80'
        restart: always
